name: CI/CD Demo
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Test
        run: |
          npm ci
          npm test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ccloveak/cicd-demo-image:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}       
        run: |
          echo "$PRIVATE_KEY" > private_key.pem && chmod 400 private_key.pem
          ssh -o StrictHostKeyChecking=no -i "private_key.pem" ec2-user@52.194.167.121 '
            docker container stop web && 
            docker image pull ccloveak/cicd-demo-image:latest &&
            docker container run --rm -d -p 80:80 --name web ccloveak/cicd-demo-image:latest
          '